/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.agileengine.smartxml;

import com.agileengine.smartxml.comparison.DefaultComparisionStrategy;
import com.agileengine.smartxml.comparison.ElementComparisonStrategy;
import org.apache.log4j.BasicConfigurator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;

public class App {
    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        BasicConfigurator.configure();

        if(3 > args.length){
            LOGGER.info("Missing parameters, please enter all required parameters");
            System.exit(1);
        }

        String targetFilePath = args[0];
        String comparisonFilePath = args[1];
        String targetElementId = args[2];

        var targetFile = new File(targetFilePath);
        var comparisonFile = new File(comparisonFilePath);
        ElementComparisonStrategy comparisionStrategy = new DefaultComparisionStrategy();

        var smartXmlAnalyzer = SmartXmlAnalyzer.createAnalyzer(targetFile, comparisonFile, comparisionStrategy);
        var matchedElement = smartXmlAnalyzer.GetMatchedElement(targetElementId);

        if (matchedElement.isPresent()) {
            LOGGER.info("Matched element path:" + matchedElement.get().getPath());
        } else {
            LOGGER.info("No elements has been matched");
        }
    }
}
